
### 菜单列表
POST {{host}}/admin/menu_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "menu_name": ""
}

### 新建菜单
POST {{host}}/admin/menu_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "api_url": "/auth/ping",
  "icon": "FrownOutlined",
  "label": "test4",
  "menu_name": "test4",
  "menu_type": 1,
  "menu_url": "test4",
  "parent_id": 0,
  "remark": "test",
  "sort": 1,
  "status": 1
}

### 删除菜单
POST {{host}}/admin/menu_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [79]
}

### 更新菜单
POST {{host}}/admin/menu_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "api_url": "/auth/ping123",
  "icon": "FrownOutlined",
  "id": 79,
  "label": "test4",
  "menu_name": "test4",
  "menu_type": 1,
  "menu_url": "test4",
  "parent_id": 0,
  "remark": "test",
  "sort": 1,
  "status": 1
}