# @import ./user.http

### 查询角色菜单 query_role_menu
POST {{host}}/admin/query_role_menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role_id": 3
}

### 更新角色菜单 update_role_menu
POST {{host}}/admin/update_role_menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role_id": 5,
  "menu_ids": [1,2,3]
}

### 角色列表 role_list
POST {{host}}/admin/role_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10
}

### 新增角色 role_save
POST {{host}}/admin/role_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "remark": "test",
  "role_name": "test",
  "sort": 1,
  "status": 1
}

### 删除角色 role_delete
POST {{host}}/admin/role_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [11]
}

### 更新角色 role_update
POST {{host}}/admin/role_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 11,
  "remark": "test123",
  "role_name": "test123",
  "sort": 1,
  "status": 1
}
