@token = {{$global.token}}

### 查看数据库连接状态
GET {{host}}/status


### 登陆 获取token
# @name login
POST {{host}}/admin/login
Content-Type: application/json

{
  "mobile": "18500000000",
  "password": "e10adc3949ba59abbe56e057f20f883e"
}

# idea
> {% client.global.set("token", response.body.data); %}

# vscode httpYac
{{
  $global.token=response.parsedBody.data;
}}


### 查询用户菜单
GET {{host}}/admin/query_user_menu
Authorization: Bearer {{token}}


### 获取用户列表
POST {{host}}/admin/user_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10,
  "mobile": "",
  "status": 1
}

### 保存用户信息
POST {{host}}/admin/user_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "mobile": "13100131000",
  "user_name": "test",
  "remark": "test"
}

### 删除用户
POST {{host}}/admin/user_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [13]
}

### 更新用户信息
POST {{host}}/admin/user_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 17,
  "mobile": "18613030351",
  "user_name": "test123",
  "remark": "test123",
  "sort": 1,
  "status": 1
}

### 更新用户密码
POST {{host}}/admin/update_user_password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 2,
  "password": "e10adc3949ba59abbe56e057f20f883e",
  "new_password": "e10adc3949ba59abbe56e057f20f883e"
}